/**
 * Mock Data for Marketing Campaigns
 * Used for development and demonstration until backend is ready
 */

import {
  Campaign,
  CampaignStatus,
  CampaignChannel,
  CampaignMetrics,
  ROIMetrics,
  AudienceSegment,
  CampaignTemplate,
  CampaignTemplateType,
  AudienceSegmentType,
} from '../types/campaign.types';

export const mockSegments: AudienceSegment[] = [
  {
    id: 'seg-001',
    name: 'Recent Bookers',
    description: 'Customers who booked in the last 30 days',
    segmentType: AudienceSegmentType.BOOKING_HISTORY,
    criteria: {
      lastBookingDaysAgo: { min: 0, max: 30 },
    },
    customerCount: 2450,
    createdAt: new Date('2024-11-01'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'seg-002',
    name: 'High-Value Customers',
    description: 'Top 20% customers by lifetime spend',
    segmentType: AudienceSegmentType.CUSTOMER_VALUE,
    criteria: {
      totalSpend: { min: 5000, max: Infinity },
    },
    customerCount: 1850,
    createdAt: new Date('2024-11-01'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'seg-003',
    name: 'Inactive Users',
    description: 'No booking in the last 90 days',
    segmentType: AudienceSegmentType.BOOKING_HISTORY,
    criteria: {
      lastBookingDaysAgo: { min: 90, max: Infinity },
    },
    customerCount: 5320,
    createdAt: new Date('2024-11-01'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'seg-004',
    name: 'US Northeast',
    description: 'Customers from northeastern United States',
    segmentType: AudienceSegmentType.GEOGRAPHIC,
    criteria: {
      location: ['NY', 'MA', 'CT', 'RI', 'VT', 'NH', 'ME', 'PA', 'NJ'],
    },
    customerCount: 3200,
    createdAt: new Date('2024-11-01'),
    updatedAt: new Date('2024-12-01'),
  },
];

export const mockTemplates: CampaignTemplate[] = [
  {
    id: 'tmpl-001',
    name: 'Summer Promotion',
    description: 'Perfect for seasonal discount campaigns',
    templateType: CampaignTemplateType.SEASONAL_PROMOTION,
    recommendedChannels: [CampaignChannel.EMAIL, CampaignChannel.SMS],
    targetSegments: [AudienceSegmentType.BOOKING_HISTORY],
    estimatedConversion: 4.2,
    emailTemplate: {
      subject: 'Limited Time: 20% Off Summer Tours',
      preheader: "Don't miss out on your summer adventure",
      htmlContent: '<p>Book your summer getaway and save 20%!</p>',
      textContent: 'Book your summer getaway and save 20%!',
      ctaButtonText: 'Explore Tours',
      ctaButtonUrl: 'https://aventrabooking.com/tours?season=summer',
    },
    smsTemplate: {
      message: 'Summer Special! Get 20% off tours. Limited time only. Book now!',
      characterCount: 0,
      includeLink: true,
    },
    createdAt: new Date('2024-11-01'),
    updatedAt: new Date('2024-12-01'),
    isActive: true,
  },
  {
    id: 'tmpl-002',
    name: 'Welcome New Customers',
    description: 'Onboarding series for new users',
    templateType: CampaignTemplateType.WELCOME_SERIES,
    recommendedChannels: [CampaignChannel.EMAIL],
    targetSegments: [AudienceSegmentType.BEHAVIORAL],
    estimatedConversion: 8.5,
    emailTemplate: {
      subject: 'Welcome to Aventra! Explore Your First Adventure',
      htmlContent: '<p>Welcome to our travel booking platform!</p>',
      textContent: 'Welcome to our travel booking platform!',
      ctaButtonText: 'Browse Tours',
      ctaButtonUrl: 'https://aventrabooking.com/tours',
    },
    createdAt: new Date('2024-11-01'),
    updatedAt: new Date('2024-12-01'),
    isActive: true,
  },
  {
    id: 'tmpl-003',
    name: 'Win Back Campaign',
    description: 'Re-engage inactive customers',
    templateType: CampaignTemplateType.WIN_BACK,
    recommendedChannels: [CampaignChannel.EMAIL, CampaignChannel.SMS],
    targetSegments: [AudienceSegmentType.BOOKING_HISTORY],
    estimatedConversion: 2.8,
    emailTemplate: {
      subject: "We Miss You! Come Back for an Exclusive Offer",
      htmlContent: '<p>We have amazing tours waiting for you!</p>',
      textContent: 'We have amazing tours waiting for you!',
      ctaButtonText: 'View Exclusive Deals',
      ctaButtonUrl: 'https://aventrabooking.com/deals/winback',
    },
    createdAt: new Date('2024-11-01'),
    updatedAt: new Date('2024-12-01'),
    isActive: true,
  },
];

export const mockMetrics: CampaignMetrics = {
  sent: 2500,
  delivered: 2450,
  bounced: 50,
  opened: 612,
  clicked: 245,
  converted: 52,
  unsubscribed: 8,
  complained: 2,
  deliveryRate: 98.0,
  openRate: 25.0,
  clickRate: 10.0,
  conversionRate: 2.12,
  bounceRate: 2.0,
  unsubscribeRate: 0.3,
  revenue: 15600,
  avgOrderValue: 300,
  avgCustomerValue: 6.24,
};

export const mockROI: ROIMetrics = {
  campaignCost: 500,
  revenue: 15600,
  profit: 15100,
  roi: 3020,
  roas: 31.2,
  costPerConversion: 9.62,
  costPerClick: 2.04,
  costPerOpen: 0.82,
  breakEvenDate: new Date('2024-12-01'),
};

export const mockCampaigns: Campaign[] = [
  {
    id: 'camp-001',
    name: 'Summer Adventure Campaign',
    description: 'Multi-channel campaign to promote summer tour packages with special discounts',
    status: CampaignStatus.ACTIVE,
    channels: [CampaignChannel.EMAIL, CampaignChannel.SMS],
    templateId: 'tmpl-001',
    audienceSegments: [mockSegments[0], mockSegments[1]],
    audienceSize: 4300,
    emailContent: {
      subject: 'Limited Time: 20% Off Summer Tours - Book Now!',
      preheader: "Don't miss out on your summer adventure",
      htmlContent:
        '<div style="padding: 20px;"><h1>Summer Special 2024</h1><p>Save 20% on all summer tour packages</p></div>',
      textContent: 'Summer Special 2024 - Save 20% on all tour packages',
      ctaButtonText: 'Explore Tours',
      ctaButtonUrl: 'https://aventrabooking.com/tours?season=summer',
    },
    smsContent: {
      message: 'Summer Special! 20% off tours. Limited time. Use code SUMMER20. Book now!',
      characterCount: 75,
      includeLink: true,
      shortUrl: 'https://t.co/xyz123',
    },
    scheduledFor: new Date('2024-12-15'),
    startDate: new Date('2024-12-10'),
    endDate: new Date('2025-01-31'),
    hasABTest: true,
    metrics: mockMetrics,
    roiTracking: mockROI,
    createdBy: 'admin',
    createdAt: new Date('2024-12-01'),
    updatedAt: new Date('2024-12-10'),
    lastScheduledAt: new Date('2024-12-10'),
  },
  {
    id: 'camp-002',
    name: 'Holiday Package Promotion',
    description: 'End-of-year holiday tour promotions',
    status: CampaignStatus.SCHEDULED,
    channels: [CampaignChannel.EMAIL],
    audienceSegments: [mockSegments[2]],
    audienceSize: 5320,
    emailContent: {
      subject: 'Holiday Magic Awaits - Exclusive December Deals',
      htmlContent: '<p>Ring in the new year with our special holiday tours</p>',
      textContent: 'Holiday tours available now with special pricing',
      ctaButtonText: 'View Holiday Tours',
      ctaButtonUrl: 'https://aventrabooking.com/holidays',
    },
    startDate: new Date('2024-12-15'),
    endDate: new Date('2024-12-31'),
    hasABTest: false,
    metrics: {
      sent: 0,
      delivered: 0,
      bounced: 0,
      converted: 0,
      deliveryRate: 0,
      conversionRate: 0,
      bounceRate: 0,
      revenue: 0,
    },
    roiTracking: {
      campaignCost: 800,
      revenue: 0,
      profit: -800,
      roi: -100,
      roas: 0,
      costPerConversion: 0,
    },
    createdBy: 'admin',
    createdAt: new Date('2024-12-05'),
    updatedAt: new Date('2024-12-05'),
  },
  {
    id: 'camp-003',
    name: 'Newsletter January Edition',
    description: 'Monthly newsletter with travel tips and exclusive offers',
    status: CampaignStatus.DRAFT,
    channels: [CampaignChannel.EMAIL],
    audienceSegments: [mockSegments[0]],
    audienceSize: 2450,
    emailContent: {
      subject: 'January Travel Inspiration & Exclusive Deals',
      htmlContent: '<p>Your monthly dose of travel inspiration</p>',
      textContent: 'Your monthly dose of travel inspiration and exclusive deals',
      ctaButtonText: 'Read Full Newsletter',
      ctaButtonUrl: 'https://aventrabooking.com/newsletter/jan-2025',
    },
    startDate: new Date('2024-12-20'),
    endDate: new Date('2024-12-20'),
    hasABTest: false,
    metrics: {
      sent: 0,
      delivered: 0,
      bounced: 0,
      converted: 0,
      deliveryRate: 0,
      conversionRate: 0,
      bounceRate: 0,
      revenue: 0,
    },
    roiTracking: {
      campaignCost: 0,
      revenue: 0,
      profit: 0,
      roi: 0,
      roas: 0,
      costPerConversion: 0,
    },
    createdBy: 'admin',
    createdAt: new Date('2024-12-08'),
    updatedAt: new Date('2024-12-08'),
  },
];
