import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react';

type Language = 'en' | 'sv';

// Dictionary of all text in the app
const translations = {
  en: {
    common: {
      loading: "Loading...",
      next: "Next",
      back: "Back",
      submit: "Submit",
      cancel: "Cancel",
      pay: "Pay",
      details: "Details",
      close: "Close",
      processing: "Processing...",
    },
    nav: {
      tours: "Tours",
      myPages: "My Pages",
      dashboard: "Dashboard",
      crm: "CRM & Bookings",
      signIn: "Sign In",
      switchGuest: "Switch to Guest",
      switchAdmin: "Demo: Login as Admin",
      loggedInAs: "Logged in as",
    },
    home: {
      heroTitle: "Discover the Nordic Wild",
      heroSubtitle: "Unforgettable expeditions and guided tours in Sweden's most spectacular landscapes.",
      exploreBtn: "Explore Tours",
      upcomingTitle: "Upcoming Adventures",
      trustedBy: "Trusted by Adventurers",
      level: "Level",
      days: "Days",
      spotsLeft: "spots left",
      next: "Next",
      fullyBooked: "Fully Booked",
    },
    tourDetails: {
      about: "About this adventure",
      highlights: "Highlights",
      itinerary: "Itinerary",
      day: "Day",
      bookCardTitle: "Book this tour",
      nextDeparture: "Next Departure",
      securePayment: "Secure payment via Stripe",
      freeCancel: "Free cancellation up to 30 days",
      bookNow: "Book Now",
      startingFrom: "Starting from",
      maxPeople: "Max 12 People",
      guideIncluded: "Professional guide included",
      fullyBooked: "Fully Booked",
      fullyBookedInfo: "This tour is currently full.",
      joinWaitlistInfo: "Join our waitlist to be notified if a spot becomes available.",
      joinWaitlist: "Join Waitlist",
    },
    booking: {
      steps: {
        overview: "Overview",
        details: "Your Details",
        payment: "Payment",
        done: "Done",
      },
      customize: {
        title: "Customize your trip",
        subtitle: "Select date and travelers for",
        departureDate: "Departure Date",
        travelers: "Number of Travelers",
        people: "people",
      },
      payer: {
        title: "Step 1: Who is paying?",
        tooltip: "The booking confirmation and receipt will be sent to this person.",
        firstName: "First Name",
        lastName: "Last Name",
        country: "Country",
        address: "Street Address",
        zip: "Zip Code",
        city: "City",
        phone: "Phone",
        email: "Email",
        streetAndNumber: "Street and number",
        yyyymmdd: "YYYYMMDD",
        enterPromoCode: "Enter promo code",
      },
      traveler: {
        sectionTitle: "Traveler Information",
        title: "Traveler",
        sameAsPayer: "Same person as payer",
        ssn: "Date of Birth / SSN (8 digits)",
        companion: "Travel Companion (Optional)",
        companionPlaceholder: "Enter details of your travel companion if any",
        preferences: "Room Preferences & Dietary Requirements",
        preferencesPlaceholder: "E.g., Vegetarian, Double bed request...",
      },
      payment: {
        title: "Payment Details",
        scheduleTitle: "Payment Schedule",
        payNow: "Pay Now (Deposit)",
        payLater: "Remaining Balance",
        dueToday: "Due Today",
        dueLater: "Due 60 days before trip",
        cardDetails: "Credit Card",
        cardNumber: "Card number",
        expiry: "MM / YY",
        cvc: "CVC",
        holderName: "Cardholder Name",
        agree: "I agree to the",
        terms: "Booking Terms",
        privacy: "Privacy Policy",
        payBtn: "Pay Deposit",
        nextStep: "Next Step",
      },
      confirmation: {
        title: "Booking Confirmed!",
        subtitle: "Your adventure is secured.",
        secured: "is confirmed and secured",
        ref: "Booking Reference",
        totalPaid: "Total Paid Now",
        remaining: "Remaining Balance",
        emailSent: "A confirmation email has been sent to",
        homeBtn: "Back to Home",
        myPagesBtn: "Go to My Pages",
        prepareForTrip: "Prepare for Your Trip",
        visitMyPages: "Visit \"My Pages\" to access your trip preparation guide and packing list.",
      },
      summary: {
        title: "Summary",
        product: "Product",
        date: "Date",
        travelers: "Travelers",
        totalPrice: "Total Price",
        toPay: "To Pay",
        vatMsg: "Includes VAT and booking fees.",
        secureMsg: "Secure SSL Payment",
      }
    },
    myPages: {
      title: "My Bookings",
      welcome: "Welcome back! Manage your upcoming trips here.",
      upcoming: "Upcoming Trips",
      noTrips: "No upcoming trips booked yet.",
      exploreText: "Start planning your next adventure today!",
      browseBtn: "Browse Tours",
      departureDate: "Departure Date",
      traveler: "Traveler",
      travelers: "Travelers",
      bookedOn: "Booked on",
      bookingRef: "Booking Reference",
      contactPerson: "Contact Person",
      paymentDetails: "Payment Details",
      totalAmount: "Total Amount",
      paidAmount: "Paid",
      remainingBalance: "Remaining Balance",
      reminderTitle: "Payment Reminder",
      reminderText: "Remaining balance is due 60 days before departure.",
      fullyPaid: "Fully Paid",
      transactionId: "Transaction ID",
      payer: "Payer",
    },
    waitlist: {
      title: "Join Waitlist",
      infoTitle: "Tour Currently Full.",
      infoText: "We'll notify you as soon as a spot becomes available.",
      participants: "Number of Participants",
      preferredDate: "Preferred Date (Optional)",
      message: "Additional Message (Optional)",
      messagePlaceholder: "Tell us about your preferences or questions...",
      submitBtn: "Submit Request",
      successTitle: "You're on the List!",
      successMessage: "We'll notify you if a spot opens up for this tour.",
    },
    admin: {
      dashboard: "Dashboard",
      bookings: "Bookings",
      allBookings: "All Bookings",
      waitlist: "Waitlist",
      marketing: "Marketing",
      promoCodes: "Promo Codes",
      emailTemplates: "Email Templates",
      customers: "Customers",
      customerList: "Customer List",
      customerGroups: "Customer Groups",
      communicationLogs: "Communication Logs",
      tours: "Tours",
      tourManagement: "Tour Management",
      pricingAvailability: "Pricing & Availability",
      itineraries: "Itineraries",
      addons: "Add-ons",
      finance: "Finance",
      paymentsRefunds: "Payments & Refunds",
      invoices: "Invoices",
      reports: "Reports",
      fortnoxIntegration: "Fortnox Integration",
      settings: "Settings",
      companyInfo: "Company Info",
      userManagement: "User Management",
      rolesPermissions: "Roles & Permissions",
      emailSettings: "Email Settings",
      systemLogs: "System Logs",
      managementPortal: "Management Portal",
      needHelp: "Need Help?",
      helpText: "Check our documentation or contact support",
      // Common admin actions and labels
      create: "Create",
      edit: "Edit",
      delete: "Delete",
      save: "Save",
      cancel: "Cancel",
      search: "Search",
      filter: "Filter",
      export: "Export",
      import: "Import",
      preview: "Preview",
      test: "Test",
      send: "Send",
      view: "View",
      copy: "Copy",
      active: "Active",
      inactive: "Inactive",
      draft: "Draft",
      published: "Published",
      archived: "Archived",
      // KPIs and Dashboard
      totalRevenue: "Total Revenue",
      monthlyRevenue: "Monthly Revenue",
      activeBookings: "Active Bookings",
      customerSatisfaction: "Customer Satisfaction",
      occupancyRate: "Occupancy Rate",
      conversionRate: "Conversion Rate",
      bookingManagement: "Booking Management",
      customerManagement: "Customer Management",
      financialOperations: "Financial Operations",
      tourManagement2: "Tour Management",
      marketingCampaigns: "Marketing Campaigns",
      systemAdministration: "System Administration",
      totalCustomers: "Total Customers",
      repeatRate: "Repeat Rate",
      kpiTitle: "Key Performance Indicators",
      systemAlertsTitle: "System Alerts & Notifications",
      // Email Templates specific
      manageEmailTemplates: "Manage your email templates for automated communications",
      createTemplate: "Create Template",
      searchTemplates: "Search templates...",
      allCategories: "All Categories",
      allStatuses: "All Statuses",
      allLanguages: "All Languages",
      bookingConfirmation: "Booking Confirmation",
      confirmationEmailBooking: "Confirmation email sent when a booking is successfully created",
      paymentReceipt: "Payment Receipt",
      receiptEmailPayment: "Receipt sent after a successful payment",
      tourReminder: "Tour Reminder",
      reminderEmailTour: "Reminder email sent before tour departure",
      templateVersion: "Version",
      sent: "Sent",
      languages: "Languages",
      templateName: "Template Name",
      category: "Category",
      status: "Status",
      lastModified: "Last Modified",
      actions: "Actions",
      // User Management
      viewDetails: "View Details",
      editUser: "Edit User",
      deleteUser: "Delete User",
      addUser: "Add User",
      inviteUser: "Invite User",
      // Roles & Permissions
      totalRoles: "Total Roles",
      customRoles: "Custom Roles",
      totalPermissions: "Total Permissions",
      lastUpdated: "Last Updated",
      // Email Editor
      fontSize: "Font Size",
      alignLeft: "Align Left",
      alignCenter: "Align Center",
      alignRight: "Align Right",
      bulletList: "Bullet List",
      numberedList: "Numbered List",
      insertLink: "Insert Link",
      insertImage: "Insert Image",
      insertPlaceholder: "Insert Placeholder",
      insertVariable: "Insert Variable",
      formatInstructions: "Use the toolbar to format your email. Click \"Insert Variable\" to add dynamic content placeholders.",
      // Campaign Manager
      marketingCampaignsTitle: "Marketing Campaigns",
      // Finance
      totalBookings: "Total Bookings",
      revenueGrowth: "Revenue Growth",
      grossProfit: "Gross Profit",
      netProfit: "Net Profit",
      // Tours
      gridView: "Grid View",
      listView: "List View",
      viewDetailsTour: "View Details",
      editTour: "Edit Tour",
      duplicateTour: "Duplicate Tour",
      deleteTour: "Delete Tour",
      imageUrl: "Image URL",
      // Customer Management
      streetAddress: "Street Address",
      zipCode: "Zip Code",
      fullName: "Full name",
      firstName: "First Name",
      lastName: "Last Name",
      roomPref: "Room Pref",
      fullAddress: "Full address",
      photoCaption: "Photo caption",
      startingPoint: "Starting point",
      maxParticipants: "Max participants",
      // Communication
      totalCommunications: "Total Communications",
      deliveryRate: "Delivery Rate",
      readRate: "Read Rate",
      clearFilters: "Clear filters",
      copyContent: "Copy content",
      moreOptions: "More options",
      deleteRule: "Delete rule",
      totalMembers: "Total Members",
      viewAnalytics: "View Analytics",
      editGroup: "Edit Group",
      exportMembers: "Export Members",
      // Email Preview
      desktopView: "Desktop View",
      mobileView: "Mobile View",
      refreshPreview: "Refresh Preview",
      // Forms
      emailSubject: "Email subject",
      variantName: "Variant name",
      // A/B Testing and Analytics
      avgPrice: "Avg Price",
      finalPrice: "Final Price",
      // Misc
      companyLogo: "Company Logo",
      openMenu: "Open menu",
      closeNotification: "Close notification",
      unsavedChanges: "You have unsaved changes. Click the \"Save Changes\" button to apply them.",
      visitMyPages: "Visit \"My Pages\" to access your trip preparation guide and packing list.",
      superAdmin: "Super Admin",
      examplePermissions: "Example: For support@swett.com, select only \"Booking Management\" and \"Customer",
      johnDoe: "John Doe",
    },
    footer: {
      tagline: "Premium guided tours and expeditions in Scandinavia.",
      support: "Support",
      contact: "Contact Us",
      faq: "FAQ",
      cancelPolicy: "Avbokningsregler",
      secure: "Säkra Betalningar",
      rights: "Alla rättigheter förbehållna.",
    }
  },
  sv: {
    common: {
      loading: "Laddar...",
      next: "Nästa",
      back: "Tillbaka",
      submit: "Skicka",
      cancel: "Avbryt",
      pay: "Betala",
      details: "Detaljer",
      close: "Stäng",
      processing: "Bearbetar...",
    },
    nav: {
      tours: "Turer",
      myPages: "Mina Sidor",
      dashboard: "Panel",
      crm: "Bokningar & CRM",
      signIn: "Logga in",
      switchGuest: "Byt till gäst",
      switchAdmin: "Demo: Logga in som Admin",
      loggedInAs: "Inloggad som",
    },
    home: {
      heroTitle: "Upptäck Nordens Vildmark",
      heroSubtitle: "Oförglömliga expeditioner och guidade turer i Sveriges mest spektakulära landskap.",
      exploreBtn: "Utforska Turer",
      upcomingTitle: "Kommande Äventyr",
      trustedBy: "Betrodd av Äventyrare",
      level: "Nivå",
      days: "Dagar",
      spotsLeft: "platser kvar",
      next: "Nästa",
      fullyBooked: "Fullbokad",
    },
    tourDetails: {
      about: "Om äventyret",
      highlights: "Höjdpunkter",
      itinerary: "Resplan",
      day: "Dag",
      bookCardTitle: "Boka denna tur",
      nextDeparture: "Nästa Avresa",
      securePayment: "Säker betalning via Stripe",
      freeCancel: "Gratis avbokning upp till 30 dagar",
      bookNow: "Boka Nu",
      startingFrom: "Från",
      maxPeople: "Max 12 Personer",
      guideIncluded: "Professionell guide inkluderad",
      fullyBooked: "Fullbokad",
      fullyBookedInfo: "Denna tur är för närvarande fullbokad.",
      joinWaitlistInfo: "Gå med i vår väntelista för att få besked om en plats blir ledig.",
      joinWaitlist: "Gå med i Väntelistan",
    },
    booking: {
      steps: {
        overview: "Översikt",
        details: "Dina uppgifter",
        payment: "Betalning",
        done: "Klart",
      },
      customize: {
        title: "Skräddarsy din resa",
        subtitle: "Välj datum och resenärer för",
        departureDate: "Avresedatum",
        travelers: "Antal resenärer",
        people: "personer",
      },
      payer: {
        title: "Steg 1: Vem betalar?",
        tooltip: "Bokningsbekräftelsen och kvittot skickas till denna person.",
        firstName: "Förnamn",
        lastName: "Efternamn",
        country: "Land",
        address: "Gatuadress",
        zip: "Postnummer",
        city: "Ort",
        phone: "Telefon",
        email: "E-post",
        streetAndNumber: "Gata och nummer",
        yyyymmdd: "ÅÅÅÅMMDD",
        enterPromoCode: "Ange kampanjkod",
      },
      traveler: {
        sectionTitle: "Resenärsinformation",
        title: "Resenär",
        sameAsPayer: "Samma person som betalar",
        ssn: "Födelsedatum / Personnr (8 siffror)",
        companion: "Resesällskap (Valfritt)",
        companionPlaceholder: "Ange detaljer om ditt resesällskap",
        preferences: "Rumsönskemål & Kost",
        preferencesPlaceholder: "T.ex. Vegetarian, Dubbelsäng...",
      },
      payment: {
        title: "Betalningsuppgifter",
        scheduleTitle: "Betalningsplan",
        payNow: "Betala nu (Anmälningsavgift)",
        payLater: "Kvarstående belopp",
        dueToday: "Betalas idag",
        dueLater: "Betalas 60 dagar innan avresa",
        cardDetails: "Kreditkort",
        cardNumber: "Kortnummer",
        expiry: "MM / ÅÅ",
        cvc: "CVC",
        holderName: "Kortinnehavarens namn",
        agree: "Jag godkänner",
        terms: "Bokningsvillkor",
        privacy: "Integritetspolicy",
        payBtn: "Betala Anmälningsavgift",
        nextStep: "Nästa Steg",
      },
      confirmation: {
        title: "Bokning Bekräftad!",
        subtitle: "Ditt äventyr är säkrat.",
        secured: "är bekräftad och säkrad",
        ref: "Bokningsreferens",
        totalPaid: "Totalt betalat nu",
        remaining: "Kvarstående belopp",
        emailSent: "Ett bekräftelsemail har skickats till",
        homeBtn: "Tillbaka till start",
        myPagesBtn: "Gå till Mina Sidor",
        prepareForTrip: "Förbered dig för din resa",
        visitMyPages: "Besök \"Mina Sidor\" för att få tillgång till din reseförberedelseguide och packningslista.",
      },
      summary: {
        title: "Sammanfattning",
        product: "Produkt",
        date: "Datum",
        travelers: "Resenärer",
        totalPrice: "Totalt Pris",
        toPay: "Att betala",
        vatMsg: "Inkluderar moms och avgifter.",
        secureMsg: "Säker SSL-betalning",
      }
    },
    myPages: {
      title: "Mina Bokningar",
      welcome: "Välkommen tillbaka! Hantera dina kommande resor här.",
      upcoming: "Kommande Resor",
      noTrips: "Inga kommande resor bokade än.",
      exploreText: "Börja planera ditt nästa äventyr idag!",
      browseBtn: "Bläddra bland turer",
      departureDate: "Avresedatum",
      traveler: "Resenär",
      travelers: "Resenärer",
      bookedOn: "Bokad den",
      bookingRef: "Bokningsreferens",
      contactPerson: "Kontaktperson",
      paymentDetails: "Betalningsdetaljer",
      totalAmount: "Totalt belopp",
      paidAmount: "Betalt",
      remainingBalance: "Kvarstående belopp",
      reminderTitle: "Betalningspåminnelse",
      reminderText: "Resterande belopp ska betalas 60 dagar före avresa.",
      fullyPaid: "Helt betald",
      transactionId: "Transaktions-ID",
      payer: "Betalare",
    },
    waitlist: {
      title: "Gå med i Väntelistan",
      infoTitle: "Turen är för närvarande fullbokad.",
      infoText: "Vi meddelar dig så snart en plats blir ledig.",
      participants: "Antal Deltagare",
      preferredDate: "Önskat Datum (Valfritt)",
      message: "Ytterligare Meddelande (Valfritt)",
      messagePlaceholder: "Berätta om dina preferenser eller frågor...",
      submitBtn: "Skicka Förfrågan",
      successTitle: "Du är med på listan!",
      successMessage: "Vi meddelar dig om en plats öppnas för denna tur.",
    },
    admin: {
      dashboard: "Instrumentpanel",
      bookings: "Bokningar",
      allBookings: "Alla Bokningar",
      waitlist: "Väntelista",
      marketing: "Marknadsföring",
      promoCodes: "Kampanjkoder",
      emailTemplates: "E-postmallar",
      customers: "Kunder",
      customerList: "Kundlista",
      customerGroups: "Kundgrupper",
      communicationLogs: "Kommunikationsloggar",
      tours: "Turer",
      tourManagement: "Turhantering",
      pricingAvailability: "Priser & Tillgänglighet",
      itineraries: "Resplaner",
      addons: "Tillägg",
      finance: "Ekonomi",
      paymentsRefunds: "Betalningar & Återbetalningar",
      invoices: "Fakturor",
      reports: "Rapporter",
      fortnoxIntegration: "Fortnox-integration",
      settings: "Inställningar",
      companyInfo: "Företagsinformation",
      userManagement: "Användarhantering",
      rolesPermissions: "Roller & Behörigheter",
      emailSettings: "E-postinställningar",
      systemLogs: "Systemloggar",
      managementPortal: "Hanteringskontrollpanel",
      needHelp: "Behöver du hjälp?",
      helpText: "Läs vår dokumentation eller kontakta support",
      // Common admin actions and labels
      create: "Skapa",
      edit: "Redigera",
      delete: "Radera",
      save: "Spara",
      cancel: "Avbryt",
      search: "Sök",
      filter: "Filtrera",
      export: "Exportera",
      import: "Importera",
      preview: "Förhandsgranska",
      test: "Testa",
      send: "Skicka",
      view: "Visa",
      copy: "Kopiera",
      active: "Aktiv",
      inactive: "Inaktiv",
      draft: "Utkast",
      published: "Publicerad",
      archived: "Arkiverad",
      // KPIs and Dashboard
      totalRevenue: "Total Intäkt",
      monthlyRevenue: "Månadsintäkt",
      activeBookings: "Aktiva Bokningar",
      customerSatisfaction: "Kundnöjdhet",
      occupancyRate: "Beläggningsgrad",
      conversionRate: "Konverteringsgrad",
      bookingManagement: "Bokningshantering",
      customerManagement: "Kundhantering",
      financialOperations: "Ekonomioperationer",
      tourManagement2: "Turhantering",
      marketingCampaigns: "Marknadsföringskampanjer",
      systemAdministration: "Systemadministration",
      totalCustomers: "Totalt Antal Kunder",
      repeatRate: "Återköpsgrad",
      kpiTitle: "Nyckeltal",
      systemAlertsTitle: "Systemvarningar & Notifieringar",
      // Email Templates specific
      manageEmailTemplates: "Hantera dina e-postmallar för automatiserad kommunikation",
      createTemplate: "Skapa Mall",
      searchTemplates: "Sök mallar...",
      allCategories: "Alla Kategorier",
      allStatuses: "Alla Status",
      allLanguages: "Alla Språk",
      bookingConfirmation: "Bokningsbekräftelse",
      confirmationEmailBooking: "Bekräftelseemail skickad när en bokning skapas framgångsrikt",
      paymentReceipt: "Betalningskvitto",
      receiptEmailPayment: "Kvitto skickat efter en framgångsrik betalning",
      tourReminder: "Turpåminnelse",
      reminderEmailTour: "Påminnelseemail skickat före turavgång",
      templateVersion: "Version",
      sent: "Skickat",
      languages: "Språk",
      templateName: "Mallnamn",
      category: "Kategori",
      status: "Status",
      lastModified: "Senast ändrad",
      actions: "Åtgärder",
      // User Management
      viewDetails: "Visa Detaljer",
      editUser: "Redigera Användare",
      deleteUser: "Radera Användare",
      addUser: "Lägg till Användare",
      inviteUser: "Bjud in Användare",
      // Roles & Permissions
      totalRoles: "Totalt Antal Roller",
      customRoles: "Anpassade Roller",
      totalPermissions: "Totalt Antal Behörigheter",
      lastUpdated: "Senast Uppdaterad",
      // Email Editor
      fontSize: "Teckenstorlek",
      alignLeft: "Vänsterjustera",
      alignCenter: "Centrera",
      alignRight: "Högerjustera",
      bulletList: "Punktlista",
      numberedList: "Numrerad Lista",
      insertLink: "Infoga Länk",
      insertImage: "Infoga Bild",
      insertPlaceholder: "Infoga Platshållare",
      insertVariable: "Infoga Variabel",
      formatInstructions: "Använd verktygsfältet för att formatera ditt e-postmeddelande. Klicka på \"Infoga Variabel\" för att lägga till dynamiska innehållsplatshållare.",
      // Campaign Manager
      marketingCampaignsTitle: "Marknadsföringskampanjer",
      // Finance
      totalBookings: "Totalt Antal Bokningar",
      revenueGrowth: "Intäktstillväxt",
      grossProfit: "Bruttovinst",
      netProfit: "Nettovinst",
      // Tours
      gridView: "Rutnätsvy",
      listView: "Listvy",
      viewDetailsTour: "Visa Detaljer",
      editTour: "Redigera Tur",
      duplicateTour: "Duplicera Tur",
      deleteTour: "Radera Tur",
      imageUrl: "Bild-URL",
      // Customer Management
      streetAddress: "Gatuadress",
      zipCode: "Postnummer",
      fullName: "Fullständigt namn",
      firstName: "Förnamn",
      lastName: "Efternamn",
      roomPref: "Rumsönskemål",
      fullAddress: "Fullständig adress",
      photoCaption: "Bildtext",
      startingPoint: "Startpunkt",
      maxParticipants: "Max deltagare",
      // Communication
      totalCommunications: "Total Kommunikation",
      deliveryRate: "Leveransgrad",
      readRate: "Läsgrad",
      clearFilters: "Rensa filter",
      copyContent: "Kopiera innehåll",
      moreOptions: "Fler alternativ",
      deleteRule: "Radera regel",
      totalMembers: "Totalt Antal Medlemmar",
      viewAnalytics: "Visa Analys",
      editGroup: "Redigera Grupp",
      exportMembers: "Exportera Medlemmar",
      // Email Preview
      desktopView: "Skrivbordsvy",
      mobileView: "Mobilvy",
      refreshPreview: "Uppdatera Förhandsgranskning",
      // Forms
      emailSubject: "E-postämne",
      variantName: "Variantnamn",
      // A/B Testing and Analytics
      avgPrice: "Genomsnittspris",
      finalPrice: "Slutpris",
      // Misc
      companyLogo: "Företagslogotyp",
      openMenu: "Öppna meny",
      closeNotification: "Stäng notifiering",
      unsavedChanges: "Du har osparade ändringar. Klicka på knappen \"Spara Ändringar\" för att tillämpa dem.",
      visitMyPages: "Besök \"Mina Sidor\" för att få tillgång till din reseförberedelseguide och packningslista.",
      superAdmin: "Superadministratör",
      examplePermissions: "Exempel: För support@swett.com, välj endast \"Bokningshantering\" och \"Kund",
      johnDoe: "Johan Svensson",
    },
    footer: {
      tagline: "Premium guidade turer och expeditioner i Skandinavien.",
      support: "Support",
      contact: "Kontakta oss",
      faq: "FAQ",
      cancelPolicy: "Avbokningsregler",
      secure: "Säkra Betalningar",
      rights: "Alla rättigheter förbehållna.",
    }
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children?: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>('en');
  const [isInitialized, setIsInitialized] = useState(false);

  // Initialize language from localStorage on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem('preferredLanguage') as Language | null;
    if (savedLanguage === 'en' || savedLanguage === 'sv') {
      setLanguageState(savedLanguage);
    }
    setIsInitialized(true);
  }, []);

  // Update localStorage when language changes
  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('preferredLanguage', lang);
  };

  // Helper function to get nested object value by string key (e.g. 'nav.tours')
  const t = (path: string): string => {
    const keys = path.split('.');
    let current: any = translations[language];
    
    for (const key of keys) {
      if (current[key] === undefined) {
        console.warn(`Translation missing for key: ${path} in language: ${language}`);
        return path;
      }
      current = current[key];
    }
    
    return typeof current === 'string' ? current : path;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
};